import type { Metadata } from "next";
import "./globals.css";
import Header from './ui/Header'
import Footer from "./ui/Footer";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

export const metadata: Metadata = {
  title: "Leet Trader",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className='overflow-x-hidden'
      >

          <Header />


        {children}
        {/* <LoadingSkeleton /> */}
        <Footer />
      </body>
    </html>
  );
}
