import type { Metadata } from "next";
import "./globals.css";
import Header from './ui/Header'
import Navigation from "./ui/Navigation";
import LoadingSkeleton from "./components/LoadingAnimation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className='overflow-hidden'
      >
        <Header />
        
        {children}
        {/* <LoadingSkeleton /> */}
      </body>
    </html>
  );
}
